### ISSUE TITLE
Understanding how the convolution is done

### ISSUE THREAD

**Issue by samridhim** [kundajelab/dfim#2]
As I understand, the input to the convolution is a 3D array which has 30k sequences encoded as a one hot vector whose dimensions is len(input sequence) x 4. All 30k of which are stored in a numpy array. Looking at the supplementary paper and the example model architecture, the convolution is done as a 1D convolution. I am confused so as to how a 1D convolution works in an input which is 3D like the one we have?

**Comment by akundaje** [comment]
No. Each of the 30K sequences is a training example and each sequence is  a
one-hot encoded 2D matrix of length L with 4 channels (A,C,G,T). So 1D
convolutions operate on the sequences.

Anshul

**Comment by samridhim** [comment]
Thank you! 
Is the working similar to the DeepBind Architecture?

**Comment by akundaje** [comment]
It's a different architecture but yeah the 1D convolutions are based on the
same principle

**Comment by samridhim** [comment]
Thanks a lot!

**Comment by samridhim** [comment]
What was the accuracy of the CNN on the classification task?

**Comment by akundaje** [comment]
Please read the paper. All the details are in there.

Thanks
Anshul

**Comment by samridhim** [comment]
Okay, Thanks!
Was only focusing on the supplementary, so didn't check the main paper. Thanks a lot!!
